apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:  
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas" 
  labels: 
    app.kubernetes.io/instance: rag2-aug-1-vllm
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name:  rag2-aug-1-vllm
    app.kubernetes.io/part-of: rag2-aug-1-vllm  
  name: rag2-aug-1-vllm
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance:  rag2-aug-1-vllm 
  template:
    metadata: 
      labels:
        app.kubernetes.io/instance:  rag2-aug-1-vllm
    spec:
      containers:
      - env:
        - name: MODEL_ENDPOINT
          value: http://rag2-aug-1-vllm-model-server:8001
        - name: MODEL_NAME
          value: "instructlab/granite-7b-lab"
        image:  quay.io/redhat-ai-dev/ai-template-bootstrap-app:latest
        name: app-interface
        ports:
        - containerPort: 8501
        securityContext:
          runAsNonRoot: true
      - image: quay.io/redhat-ai-dev/chroma:latest
        name: database
        ports:
        - containerPort: 8000
        securityContext:
          runAsNonRoot: true