apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: rag2-aug-1-vllm
  janus-idp.io/tekton: rag2-aug-1-vllm
  backstage.io/kubernetes-id: rag2-aug-1-vllm
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: rag2-aug-1-vllm
resources: 
- initialize-namespace.yaml
- pvc.yaml
- deployment-model-server.yaml
- service-model-server.yaml
- deployment.yaml
- route.yaml
- service.yaml